import Head from 'next/head';
import LoginForm from '@/components/LoginForm';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className="px-4 m-0 bg-gradient-to-br from-primary-color to-blue-400 min-h-screen">
					<LoginForm />
				</div>
			</main>
		</>
	);
}
